default_language_version.python = "3.14"

[[repos]]
repo = "local"

[[repos.hooks]]
id = "ruff"
name = "ruff"
language = "system"
entry = "just lint-fix"
files = "\\.py$"
pass_filenames = false

[[repos.hooks]]
id = "ty"
name = "ty"
language = "system"
entry = "just ty"
files = "\\.py$"
pass_filenames = false
