# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-05-06T08:13:43+00:00

from __future__ import annotations

from datetime import date
from typing import Any, Literal

from pydantic import BaseModel, Field, RootModel


class CCEStageModel(BaseModel):
    is_saturation_pressure: bool = Field(..., title="Is Saturation Pressure")
    pressure: float = Field(..., title="Pressure")
    relative_oil_volume: float | None = Field(None, title="Relative Oil Volume")
    relative_total_volume: float | None = Field(None, title="Relative Total Volume")
    single_phase_density: float | None = Field(None, title="Single Phase Density")
    z_factor: float | None = Field(None, title="Z Factor")


class CVDStageModel(BaseModel):
    cumulative_moles_removed: float | None = Field(None, title="Cumulative Moles Removed")
    gas_density: float | None = Field(None, title="Gas Density")
    gas_plus_fraction_mw: float | None = Field(None, title="Gas Plus Fraction Mw")
    gas_specific_gravity: float | None = Field(None, title="Gas Specific Gravity")
    gas_viscosity: float | None = Field(None, title="Gas Viscosity")
    gas_z_factor: float | None = Field(None, title="Gas Z Factor")
    incremental_moles_removed: float | None = Field(None, title="Incremental Moles Removed")
    is_saturation_pressure: bool = Field(..., title="Is Saturation Pressure")
    oil_density: float | None = Field(None, title="Oil Density")
    pressure: float = Field(..., title="Pressure")
    relative_oil_volume: float | None = Field(None, title="Relative Oil Volume")


class ClientCredentials(BaseModel):
    client_id: str = Field(..., title="Client Id")
    client_secret: str = Field(..., title="Client Secret")


class MassAmount(RootModel[float]):
    root: float = Field(..., ge=0.0, title="Mass Amount")


class MolarAmount(RootModel[float]):
    root: float = Field(..., ge=0.0, title="Molar Amount")


class Mw(RootModel[float]):
    root: float = Field(..., gt=0.0, title="Mw")


class CompositionComponentModel(BaseModel):
    input_name: str = Field(..., title="Input Name")
    mass_amount: MassAmount | None = Field(None, title="Mass Amount")
    molar_amount: MolarAmount | None = Field(None, title="Molar Amount")
    mw: Mw | None = Field(None, title="Mw")
    name: Literal[
        "Neon",
        "Argon",
        "Krypton",
        "Xeon",
        "Radon",
        "He",
        "H2",
        "N2",
        "O2",
        "CO",
        "NO",
        "N2O",
        "CO2",
        "H2S",
        "NH3",
        "SO2",
        "NO2",
        "N2O4",
        "H2O",
        "C1",
        "C2",
        "C3",
        "C-C3",
        "i-C4",
        "n-C4",
        "C4",
        "Neo-C5",
        "C-C4",
        "i-C5",
        "n-C5",
        "C5",
        "C-C5",
        "22DM-C4",
        "23DM-C4",
        "2M-C5",
        "3M-C5",
        "n-C6",
        "C6",
        "MC-C5",
        "22DM-C5",
        "Benzene",
        "24DM-C5",
        "C-C6",
        "223TM-C4",
        "33DM-C5",
        "23DM-C5",
        "2M-C6",
        "3M-C6",
        "3E-C5",
        "n-C7",
        "C7",
        "MC-C6",
        "EC-C5",
        "Toluene",
        "C-C7",
        "n-C8",
        "C8",
        "E-Benzene",
        "P-Xylene",
        "M-Xylene",
        "O-Xylene",
        "n-C9",
        "C9",
        "C-C8",
        "Cumene",
        "P-Benzene",
        "1E4M-Benzene",
        "135TM-Benzene",
        "124TM-Benzene",
        "n-C10",
        "C10",
        "123TM-Benzene",
        "n-C11",
        "C11",
        "n-C12",
        "C12",
        "Napthalen",
        "n-C13",
        "C13",
        "2M-Napthalene",
        "1M-Napthalene",
        "n-C14",
        "C14",
        "DPh-C1",
        "n-C15",
        "C15",
        "n-C16",
        "C16",
        "n-C17",
        "C17",
        "n-C18",
        "C18",
        "n-C19",
        "C19",
        "12DPh-Benzene",
        "Phenanthrene",
        "Anthracene",
        "n-C20",
        "C20",
        "n-C21",
        "C21",
        "13DPh-Benzene",
        "n-C22",
        "C22",
        "14DPh-Benzene",
        "n-C23",
        "C23",
        "n-C24",
        "C24",
        "n-C25",
        "C25",
        "n-C26",
        "C26",
        "n-C27",
        "C27",
        "n-C28",
        "C28",
        "n-C29",
        "C29",
        "n-C30",
        "C30",
        "n-C31",
        "C31",
        "n-C32",
        "C32",
        "n-C33",
        "C33",
        "n-C34",
        "C34",
        "n-C35",
        "C35",
        "n-C36",
        "C36",
        "C37",
        "C38",
        "C39",
        "C40",
        "C41",
        "C42",
        "C43",
        "C44",
        "C45",
        "C46",
        "C47",
        "C48",
        "C49",
        "C50",
        "C51",
        "C52",
        "C53",
        "C54",
        "C55",
        "C56",
        "C57",
        "C58",
        "C59",
        "C60",
        "C61",
        "C62",
        "C63",
        "C64",
        "C65",
        "C66",
        "C67",
        "C68",
        "C69",
        "C70",
        "C71",
        "C72",
        "C73",
        "C74",
        "C75",
        "C76",
        "C77",
        "C78",
        "C79",
        "C80",
        "C7M",
        "C8M",
        "C9M",
        "C10M",
        "C11M",
        "C12M",
        "C13M",
        "C14M",
        "C15M",
        "C16M",
        "C17M",
        "C18M",
        "C19M",
        "C20M",
        "C21M",
        "C22M",
        "C23M",
        "C24M",
        "C25M",
        "C26M",
        "C27M",
        "C28M",
        "C29M",
        "C30M",
        "C31M",
        "C32M",
        "C33M",
        "C34M",
        "C35M",
        "C36M",
        "C7+",
        "C8+",
        "C9+",
        "C10+",
        "C11+",
        "C12+",
        "C13+",
        "C14+",
        "C15+",
        "C16+",
        "C17+",
        "C18+",
        "C19+",
        "C20+",
        "C21+",
        "C22+",
        "C23+",
        "C24+",
        "C25+",
        "C26+",
        "C27+",
        "C28+",
        "C29+",
        "C30+",
        "C31+",
        "C32+",
        "C33+",
        "C34+",
        "C35+",
        "C36+",
        "C37+",
        "C38+",
        "C39+",
        "C40+",
        "C41+",
        "C42+",
        "C43+",
        "C44+",
        "C45+",
        "C46+",
        "C47+",
        "C48+",
        "C49+",
        "C50+",
        "C51+",
        "C52+",
        "C53+",
        "C54+",
        "C55+",
        "C56+",
        "C57+",
        "C58+",
        "C59+",
        "C60+",
        "C61+",
        "C62+",
        "C63+",
        "C64+",
        "C65+",
        "C66+",
        "C67+",
        "C68+",
        "C69+",
        "C70+",
        "C71+",
        "C72+",
        "C73+",
        "C74+",
        "C75+",
        "C76+",
        "C77+",
        "C78+",
        "C79+",
        "C80+",
    ] = Field(..., title="Name")


class CompositionModel(BaseModel):
    components: list[CompositionComponentModel] = Field(..., title="Components")


class DLEStageModel(BaseModel):
    gas_density: float | None = Field(None, title="Gas Density")
    gas_specific_gravity: float | None = Field(None, title="Gas Specific Gravity")
    gas_viscosity: float | None = Field(None, title="Gas Viscosity")
    gas_z_factor: float | None = Field(None, title="Gas Z Factor")
    gor: float | None = Field(None, title="Gor")
    is_saturation_pressure: bool = Field(..., title="Is Saturation Pressure")
    liberated_gas: float | None = Field(None, title="Liberated Gas")
    oil_density: float | None = Field(None, title="Oil Density")
    oil_fvf: float | None = Field(None, title="Oil Fvf")
    pressure: float = Field(..., title="Pressure")


class ExternalCreateRegionModel(BaseModel):
    id: int | None = Field(None, title="Id")
    name: str = Field(..., title="Name")
    note: str | None = Field(None, title="Note")
    public: bool | None = Field(None, title="Public")
    region_type: Literal[
        "single_field",
        "multi_field",
        "greater_area",
        "basin",
        "reservoir_management_unit",
        "asset",
        "country",
    ] = Field(..., title="Region Type")
    reservoir_type: Literal["Conventional", "Unconventional"] = Field(..., title="Reservoir Type")


class ExternalGetRegionModel(BaseModel):
    id: int | None = Field(None, title="Id")
    name: str | None = Field(None, title="Name")
    note: str | None = Field(None, title="Note")
    public: bool | None = Field(None, title="Public")
    region_type: (
        Literal[
            "single_field",
            "multi_field",
            "greater_area",
            "basin",
            "reservoir_management_unit",
            "asset",
            "country",
        ]
        | None
    ) = Field(None, title="Region Type")
    reservoir_type: Literal["Conventional", "Unconventional"] | None = Field(
        None, title="Reservoir Type"
    )


class ExternalGetSimpleWellModel(BaseModel):
    basin_id: float | None = Field(None, title="Basin Id")
    basin_name: str | None = Field(..., title="Basin Name")
    field_id: float | None = Field(None, title="Field Id")
    field_name: str | None = Field(..., title="Field Name")
    field_segment_id: float | None = Field(None, title="Field Segment Id")
    field_segment_name: str | None = Field(..., title="Field Segment Name")
    formation_id: float | None = Field(None, title="Formation Id")
    formation_name: str | None = Field(..., title="Formation Name")
    formation_zone_id: float | None = Field(None, title="Formation Zone Id")
    formation_zone_name: str | None = Field(..., title="Formation Zone Name")
    id: int | None = Field(None, title="Id")
    location: Any = Field(None, title="Location")
    name: str | None = Field(None, title="Name")
    region_id: int | None = Field(None, title="Region Id")
    sub_basin_id: float | None = Field(None, title="Sub Basin Id")
    sub_basin_name: str | None = Field(..., title="Sub Basin Name")
    uwi: str | None = Field(None, title="Uwi")


class ExternalIonDataModel(BaseModel):
    concentration: float | None = Field(None, title="Concentration")
    equivalence: float | None = Field(None, title="Equivalence")
    name: str = Field(..., title="Name")
    type: Literal["anion", "cation"] = Field(..., title="Type")


class ExternalRegionsListModel(BaseModel):
    regions: list[ExternalGetRegionModel] = Field(..., title="Regions")


class ExternalUpdateRegionModel(BaseModel):
    id: int | None = Field(None, title="Id")
    name: str | None = Field(None, title="Name")
    note: str | None = Field(None, title="Note")
    public: bool | None = Field(None, title="Public")
    region_type: (
        Literal[
            "single_field",
            "multi_field",
            "greater_area",
            "basin",
            "reservoir_management_unit",
            "asset",
            "country",
        ]
        | None
    ) = Field(None, title="Region Type")
    reservoir_type: Literal["Conventional", "Unconventional"] | None = Field(
        None, title="Reservoir Type"
    )


class ExternalUpdateWellItemModel(BaseModel):
    basin_id: float | None = Field(None, title="Basin Id")
    field_id: float | None = Field(None, title="Field Id")
    field_segment_id: float | None = Field(None, title="Field Segment Id")
    formation_id: float | None = Field(None, title="Formation Id")
    formation_zone_id: float | None = Field(None, title="Formation Zone Id")
    id: int = Field(..., title="Id")
    location: Any = Field(None, title="Location")
    name: str | None = Field(None, title="Name")
    region_id: int | None = Field(None, title="Region Id")
    sub_basin_id: float | None = Field(None, title="Sub Basin Id")
    uwi: str | None = Field(None, title="Uwi")


class ExternalUpdateWellModel(BaseModel):
    basin_id: float | None = Field(None, title="Basin Id")
    field_id: float | None = Field(None, title="Field Id")
    field_segment_id: float | None = Field(None, title="Field Segment Id")
    formation_id: float | None = Field(None, title="Formation Id")
    formation_zone_id: float | None = Field(None, title="Formation Zone Id")
    id: int | None = Field(None, title="Id")
    location: Any = Field(None, title="Location")
    name: str | None = Field(None, title="Name")
    region_id: int | None = Field(None, title="Region Id")
    sub_basin_id: float | None = Field(None, title="Sub Basin Id")
    uwi: str | None = Field(None, title="Uwi")


class ExternalUpdateWellsListModel(BaseModel):
    root: list[ExternalUpdateWellItemModel] = Field(..., title="Root")


class ExternalWellsListModel(BaseModel):
    wells: list[ExternalGetSimpleWellModel] = Field(..., title="Wells")


class LiberatedGasComponentModel(BaseModel):
    input_name: str = Field(..., title="Input Name")
    mw: Mw | None = Field(None, title="Mw")
    name: Literal[
        "Neon",
        "Argon",
        "Krypton",
        "Xeon",
        "Radon",
        "He",
        "H2",
        "N2",
        "O2",
        "CO",
        "NO",
        "N2O",
        "CO2",
        "H2S",
        "NH3",
        "SO2",
        "NO2",
        "N2O4",
        "H2O",
        "C1",
        "C2",
        "C3",
        "C-C3",
        "i-C4",
        "n-C4",
        "C4",
        "Neo-C5",
        "C-C4",
        "i-C5",
        "n-C5",
        "C5",
        "C-C5",
        "22DM-C4",
        "23DM-C4",
        "2M-C5",
        "3M-C5",
        "n-C6",
        "C6",
        "MC-C5",
        "22DM-C5",
        "Benzene",
        "24DM-C5",
        "C-C6",
        "223TM-C4",
        "33DM-C5",
        "23DM-C5",
        "2M-C6",
        "3M-C6",
        "3E-C5",
        "n-C7",
        "C7",
        "MC-C6",
        "EC-C5",
        "Toluene",
        "C-C7",
        "n-C8",
        "C8",
        "E-Benzene",
        "P-Xylene",
        "M-Xylene",
        "O-Xylene",
        "n-C9",
        "C9",
        "C-C8",
        "Cumene",
        "P-Benzene",
        "1E4M-Benzene",
        "135TM-Benzene",
        "124TM-Benzene",
        "n-C10",
        "C10",
        "123TM-Benzene",
        "n-C11",
        "C11",
        "n-C12",
        "C12",
        "Napthalen",
        "n-C13",
        "C13",
        "2M-Napthalene",
        "1M-Napthalene",
        "n-C14",
        "C14",
        "DPh-C1",
        "n-C15",
        "C15",
        "n-C16",
        "C16",
        "n-C17",
        "C17",
        "n-C18",
        "C18",
        "n-C19",
        "C19",
        "12DPh-Benzene",
        "Phenanthrene",
        "Anthracene",
        "n-C20",
        "C20",
        "n-C21",
        "C21",
        "13DPh-Benzene",
        "n-C22",
        "C22",
        "14DPh-Benzene",
        "n-C23",
        "C23",
        "n-C24",
        "C24",
        "n-C25",
        "C25",
        "n-C26",
        "C26",
        "n-C27",
        "C27",
        "n-C28",
        "C28",
        "n-C29",
        "C29",
        "n-C30",
        "C30",
        "n-C31",
        "C31",
        "n-C32",
        "C32",
        "n-C33",
        "C33",
        "n-C34",
        "C34",
        "n-C35",
        "C35",
        "n-C36",
        "C36",
        "C37",
        "C38",
        "C39",
        "C40",
        "C41",
        "C42",
        "C43",
        "C44",
        "C45",
        "C46",
        "C47",
        "C48",
        "C49",
        "C50",
        "C51",
        "C52",
        "C53",
        "C54",
        "C55",
        "C56",
        "C57",
        "C58",
        "C59",
        "C60",
        "C61",
        "C62",
        "C63",
        "C64",
        "C65",
        "C66",
        "C67",
        "C68",
        "C69",
        "C70",
        "C71",
        "C72",
        "C73",
        "C74",
        "C75",
        "C76",
        "C77",
        "C78",
        "C79",
        "C80",
        "C7M",
        "C8M",
        "C9M",
        "C10M",
        "C11M",
        "C12M",
        "C13M",
        "C14M",
        "C15M",
        "C16M",
        "C17M",
        "C18M",
        "C19M",
        "C20M",
        "C21M",
        "C22M",
        "C23M",
        "C24M",
        "C25M",
        "C26M",
        "C27M",
        "C28M",
        "C29M",
        "C30M",
        "C31M",
        "C32M",
        "C33M",
        "C34M",
        "C35M",
        "C36M",
        "C7+",
        "C8+",
        "C9+",
        "C10+",
        "C11+",
        "C12+",
        "C13+",
        "C14+",
        "C15+",
        "C16+",
        "C17+",
        "C18+",
        "C19+",
        "C20+",
        "C21+",
        "C22+",
        "C23+",
        "C24+",
        "C25+",
        "C26+",
        "C27+",
        "C28+",
        "C29+",
        "C30+",
        "C31+",
        "C32+",
        "C33+",
        "C34+",
        "C35+",
        "C36+",
        "C37+",
        "C38+",
        "C39+",
        "C40+",
        "C41+",
        "C42+",
        "C43+",
        "C44+",
        "C45+",
        "C46+",
        "C47+",
        "C48+",
        "C49+",
        "C50+",
        "C51+",
        "C52+",
        "C53+",
        "C54+",
        "C55+",
        "C56+",
        "C57+",
        "C58+",
        "C59+",
        "C60+",
        "C61+",
        "C62+",
        "C63+",
        "C64+",
        "C65+",
        "C66+",
        "C67+",
        "C68+",
        "C69+",
        "C70+",
        "C71+",
        "C72+",
        "C73+",
        "C74+",
        "C75+",
        "C76+",
        "C77+",
        "C78+",
        "C79+",
        "C80+",
    ] = Field(..., title="Name")


class LiberatedGasComponentMolarAmountModel(BaseModel):
    component_name: Literal[
        "Neon",
        "Argon",
        "Krypton",
        "Xeon",
        "Radon",
        "He",
        "H2",
        "N2",
        "O2",
        "CO",
        "NO",
        "N2O",
        "CO2",
        "H2S",
        "NH3",
        "SO2",
        "NO2",
        "N2O4",
        "H2O",
        "C1",
        "C2",
        "C3",
        "C-C3",
        "i-C4",
        "n-C4",
        "C4",
        "Neo-C5",
        "C-C4",
        "i-C5",
        "n-C5",
        "C5",
        "C-C5",
        "22DM-C4",
        "23DM-C4",
        "2M-C5",
        "3M-C5",
        "n-C6",
        "C6",
        "MC-C5",
        "22DM-C5",
        "Benzene",
        "24DM-C5",
        "C-C6",
        "223TM-C4",
        "33DM-C5",
        "23DM-C5",
        "2M-C6",
        "3M-C6",
        "3E-C5",
        "n-C7",
        "C7",
        "MC-C6",
        "EC-C5",
        "Toluene",
        "C-C7",
        "n-C8",
        "C8",
        "E-Benzene",
        "P-Xylene",
        "M-Xylene",
        "O-Xylene",
        "n-C9",
        "C9",
        "C-C8",
        "Cumene",
        "P-Benzene",
        "1E4M-Benzene",
        "135TM-Benzene",
        "124TM-Benzene",
        "n-C10",
        "C10",
        "123TM-Benzene",
        "n-C11",
        "C11",
        "n-C12",
        "C12",
        "Napthalen",
        "n-C13",
        "C13",
        "2M-Napthalene",
        "1M-Napthalene",
        "n-C14",
        "C14",
        "DPh-C1",
        "n-C15",
        "C15",
        "n-C16",
        "C16",
        "n-C17",
        "C17",
        "n-C18",
        "C18",
        "n-C19",
        "C19",
        "12DPh-Benzene",
        "Phenanthrene",
        "Anthracene",
        "n-C20",
        "C20",
        "n-C21",
        "C21",
        "13DPh-Benzene",
        "n-C22",
        "C22",
        "14DPh-Benzene",
        "n-C23",
        "C23",
        "n-C24",
        "C24",
        "n-C25",
        "C25",
        "n-C26",
        "C26",
        "n-C27",
        "C27",
        "n-C28",
        "C28",
        "n-C29",
        "C29",
        "n-C30",
        "C30",
        "n-C31",
        "C31",
        "n-C32",
        "C32",
        "n-C33",
        "C33",
        "n-C34",
        "C34",
        "n-C35",
        "C35",
        "n-C36",
        "C36",
        "C37",
        "C38",
        "C39",
        "C40",
        "C41",
        "C42",
        "C43",
        "C44",
        "C45",
        "C46",
        "C47",
        "C48",
        "C49",
        "C50",
        "C51",
        "C52",
        "C53",
        "C54",
        "C55",
        "C56",
        "C57",
        "C58",
        "C59",
        "C60",
        "C61",
        "C62",
        "C63",
        "C64",
        "C65",
        "C66",
        "C67",
        "C68",
        "C69",
        "C70",
        "C71",
        "C72",
        "C73",
        "C74",
        "C75",
        "C76",
        "C77",
        "C78",
        "C79",
        "C80",
        "C7M",
        "C8M",
        "C9M",
        "C10M",
        "C11M",
        "C12M",
        "C13M",
        "C14M",
        "C15M",
        "C16M",
        "C17M",
        "C18M",
        "C19M",
        "C20M",
        "C21M",
        "C22M",
        "C23M",
        "C24M",
        "C25M",
        "C26M",
        "C27M",
        "C28M",
        "C29M",
        "C30M",
        "C31M",
        "C32M",
        "C33M",
        "C34M",
        "C35M",
        "C36M",
        "C7+",
        "C8+",
        "C9+",
        "C10+",
        "C11+",
        "C12+",
        "C13+",
        "C14+",
        "C15+",
        "C16+",
        "C17+",
        "C18+",
        "C19+",
        "C20+",
        "C21+",
        "C22+",
        "C23+",
        "C24+",
        "C25+",
        "C26+",
        "C27+",
        "C28+",
        "C29+",
        "C30+",
        "C31+",
        "C32+",
        "C33+",
        "C34+",
        "C35+",
        "C36+",
        "C37+",
        "C38+",
        "C39+",
        "C40+",
        "C41+",
        "C42+",
        "C43+",
        "C44+",
        "C45+",
        "C46+",
        "C47+",
        "C48+",
        "C49+",
        "C50+",
        "C51+",
        "C52+",
        "C53+",
        "C54+",
        "C55+",
        "C56+",
        "C57+",
        "C58+",
        "C59+",
        "C60+",
        "C61+",
        "C62+",
        "C63+",
        "C64+",
        "C65+",
        "C66+",
        "C67+",
        "C68+",
        "C69+",
        "C70+",
        "C71+",
        "C72+",
        "C73+",
        "C74+",
        "C75+",
        "C76+",
        "C77+",
        "C78+",
        "C79+",
        "C80+",
    ] = Field(..., title="Component Name")
    molar_amount: MolarAmount | None = Field(None, title="Molar Amount")
    stage_number: int = Field(..., title="Stage Number")


class LiberatedGasStageModel(BaseModel):
    composition: list[LiberatedGasComponentMolarAmountModel] = Field(..., title="Composition")
    stage_number: int = Field(..., title="Stage Number")


class MSSStageModel(BaseModel):
    gas_density: float | None = Field(None, title="Gas Density")
    gas_specific_gravity: float | None = Field(None, title="Gas Specific Gravity")
    gas_viscosity: float | None = Field(None, title="Gas Viscosity")
    gas_z_factor: float | None = Field(None, title="Gas Z Factor")
    gor: float | None = Field(None, title="Gor")
    is_saturation_pressure: bool = Field(..., title="Is Saturation Pressure")
    liberated_gas: float | None = Field(None, title="Liberated Gas")
    oil_density: float | None = Field(None, title="Oil Density")
    oil_fvf: float | None = Field(None, title="Oil Fvf")
    pressure: float = Field(..., title="Pressure")
    temperature: float = Field(..., title="Temperature")


class SlimtubeRecoveryStageDataModel(BaseModel):
    fluid_transparency: float | None = Field(None, title="Fluid Transparency")
    gas_recovery: float | None = Field(None, title="Gas Recovery")
    gas_volume: float | None = Field(None, title="Gas Volume")
    injection_pressure: float | None = Field(None, title="Injection Pressure")
    oil_recovery: float | None = Field(None, title="Oil Recovery")
    oil_volume: float | None = Field(None, title="Oil Volume")
    pore_volume_injected: float | None = Field(None, title="Pore Volume Injected")
    pressure_difference: float | None = Field(None, title="Pressure Difference")
    time_elapsed: float | None = Field(None, title="Time Elapsed")


class SlimtubeStageModel(BaseModel):
    average_pressure: float | None = Field(None, title="Average Pressure")
    final_recovery: float | None = Field(None, title="Final Recovery")
    fluid_transparency_unit: Literal["%", "frac."] | None = Field(
        "%", title="Fluid Transparency Unit"
    )
    gas_recovery_unit: Literal["%", "frac."] | None = Field("%", title="Gas Recovery Unit")
    gas_volume_unit: Literal["L", "mL", "cm3", "m3"] | None = Field("L", title="Gas Volume Unit")
    injection_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field("bara", title="Injection Pressure Unit")
    is_miscible: bool | None = Field(None, title="Is Miscible")
    oil_recovery_unit: Literal["%", "frac."] | None = Field("%", title="Oil Recovery Unit")
    oil_volume_unit: Literal["L", "mL", "cm3", "m3"] | None = Field("L", title="Oil Volume Unit")
    pressure_difference_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field("bara", title="Pressure Difference Unit")
    recovery_at_1_2_pore_volumes_injected: float = Field(
        ..., title="Recovery At 1 2 Pore Volumes Injected"
    )
    recovery_at_1_pore_volumes_injected: float | None = Field(
        None, title="Recovery At 1 Pore Volumes Injected"
    )
    recovery_stage_data: list[SlimtubeRecoveryStageDataModel] = Field(
        ..., title="Recovery Stage Data"
    )
    stock_tank_oil_density: float | None = Field(None, title="Stock Tank Oil Density")
    target_injection_pressure: float = Field(..., title="Target Injection Pressure")
    temperature: float | None = Field(None, title="Temperature")
    time_elapsed_unit: Literal["sec.", "min."] | None = Field("sec.", title="Time Elapsed Unit")


class SwellTestStageCCEDataModel(BaseModel):
    pressure: float = Field(..., title="Pressure")
    relative_oil_volume: float | None = Field(None, title="Relative Oil Volume")
    relative_total_volume: float | None = Field(None, title="Relative Total Volume")
    single_phase_density: float | None = Field(None, title="Single Phase Density")


class SwellTestStageModel(BaseModel):
    cce_data: list[SwellTestStageCCEDataModel] = Field(..., title="Cce Data")
    density_at_saturation_pressure: float | None = Field(
        None, title="Density At Saturation Pressure"
    )
    gas_oil_ratio: float | None = Field(None, title="Gas Oil Ratio")
    moles_injected: float = Field(..., title="Moles Injected")
    pressure_unit: Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None = (
        Field("bara", title="Pressure Unit")
    )
    recombined_fluid_composition: CompositionModel | None = None
    relative_oil_volume_unit: Literal["Vo/Vsat (%)", "Vo/Vtot (%)", "Vo/Vsat", "Vo/Vtot"] | None = (
        Field("Vo/Vsat (%)", title="Relative Oil Volume Unit")
    )
    relative_volume_at_saturation_pressure: float | None = Field(
        None, title="Relative Volume At Saturation Pressure"
    )
    saturation_pressure: float = Field(..., title="Saturation Pressure")
    saturation_pressure_type: Literal["Dewpoint", "Bubblepoint"] = Field(
        ..., title="Saturation Pressure Type"
    )
    single_phase_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        "g/cm3", title="Single Phase Density Unit"
    )


class TBPCutModel(BaseModel):
    cumulative_mass_amount: float | None = Field(None, title="Cumulative Mass Amount")
    cumulative_volume_amount: float | None = Field(None, title="Cumulative Volume Amount")
    density: float | None = Field(None, title="Density")
    lower_temperature: float | None = Field(None, title="Lower Temperature")
    mass_amount: float | None = Field(None, title="Mass Amount")
    mw: float | None = Field(None, title="Mw")
    upper_temperature: float | None = Field(None, title="Upper Temperature")
    volume_amount: float | None = Field(None, title="Volume Amount")


class TBPExperimentModel(BaseModel):
    cumulative_mass_amount_unit: Literal["%", "frac."] | None = Field(
        "%", title="Cumulative Mass Amount Unit"
    )
    cumulative_volume_amount_unit: Literal["%", "frac."] | None = Field(
        "%", title="Cumulative Volume Amount Unit"
    )
    cuts: list[TBPCutModel] = Field(..., title="Cuts")
    density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        "g/cm3", title="Density Unit"
    )
    lower_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        "C", title="Lower Temperature Unit"
    )
    mass_amount_unit: Literal["%", "frac."] | None = Field("%", title="Mass Amount Unit")
    name: str = Field(..., title="Name")
    type: Literal["TBP"] = Field(..., title="Type")
    upper_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        "C", title="Upper Temperature Unit"
    )
    volume_amount_unit: Literal["%", "frac."] | None = Field("%", title="Volume Amount Unit")


class TokenData(BaseModel):
    access_token: str = Field(..., title="Access Token")
    expires_at: float | None = Field(0, title="Expires At")
    expires_in: int = Field(..., title="Expires In")
    token_type: str = Field(..., title="Token Type")


class VISCOStageModel(BaseModel):
    gas_viscosity: float | None = Field(None, title="Gas Viscosity")
    oil_viscosity: float | None = Field(None, title="Oil Viscosity")
    pressure: float = Field(..., title="Pressure")


class CCEExperimentModel(BaseModel):
    name: str = Field(..., title="Name")
    pressure_unit: Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None = (
        Field("bara", title="Pressure Unit")
    )
    relative_oil_volume_unit: Literal["Vo/Vsat (%)", "Vo/Vtot (%)", "Vo/Vsat", "Vo/Vtot"] | None = (
        Field("Vo/Vsat (%)", title="Relative Oil Volume Unit")
    )
    relative_total_volume_unit: Literal["Vtot/Vsat", "Vtot"] | None = Field(
        "Vtot/Vsat", title="Relative Total Volume Unit"
    )
    saturation_pressure_type: Literal["Dewpoint", "Bubblepoint"] | None = Field(
        None, title="Saturation Pressure Type"
    )
    single_phase_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        "g/cm3", title="Single Phase Density Unit"
    )
    stages: list[CCEStageModel] = Field(..., title="Stages")
    temperature: float = Field(..., title="Temperature")
    temperature_unit: Literal["C", "K", "F", "R"] = Field(..., title="Temperature Unit")
    type: Literal["CCE"] = Field(..., title="Type")


class LiberatedGasCompositionsModel(BaseModel):
    components: list[LiberatedGasComponentModel] = Field(..., title="Components")
    stages: list[LiberatedGasStageModel] = Field(..., title="Stages")


class MSSExperimentModel(BaseModel):
    gas_density_unit: Literal["SG", "kg/m3", "g/cm3", "lbm/bbl", "lbm/ft3"] | None = Field(
        "g/cm3", title="Gas Density Unit"
    )
    gas_viscosity_unit: Literal["cP", "micro-cP"] | None = Field("cP", title="Gas Viscosity Unit")
    gor_unit: (
        Literal["Sm3/Sm3", "scf/STB", "1e6-Sm3/Sm3", "MMscf/STB", "1e3-Sm3/Sm3", "Mscf/STB"] | None
    ) = Field("Sm3/Sm3", title="Gor Unit")
    liberated_gas_compositions: LiberatedGasCompositionsModel | None = None
    liberated_gas_unit: (
        Literal[
            "Sm3/Sm3",
            "Sm3/m3",
            "scf/STB",
            "scf/bbl",
            "1e6-Sm3/Sm3",
            "1e6-Sm3/m3",
            "MMscf/STB",
            "MMscf/bbl",
            "1e3-Sm3/Sm3",
            "1e3-Sm3/m3",
            "Mscf/STB",
            "Mscf/bbl",
        ]
        | None
    ) = Field("Sm3/Sm3", title="Liberated Gas Unit")
    name: str = Field(..., title="Name")
    oil_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        "g/cm3", title="Oil Density Unit"
    )
    oil_fvf_unit: Literal["m3/Sm3", "bbl/STB"] | None = Field("m3/Sm3", title="Oil Fvf Unit")
    pressure_unit: Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None = (
        Field("bara", title="Pressure Unit")
    )
    saturation_pressure_type: Literal["Dewpoint", "Bubblepoint"] | None = Field(
        None, title="Saturation Pressure Type"
    )
    single_phase_reference_pressure: float | None = Field(
        None, title="Single Phase Reference Pressure"
    )
    stages: list[MSSStageModel] = Field(..., title="Stages")
    stock_tank_oil_composition: CompositionModel | None = None
    stock_tank_oil_density: float | None = Field(None, title="Stock Tank Oil Density")
    stock_tank_oil_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Stock Tank Oil Density Unit"
    )
    stock_tank_oil_molecular_weight: float | None = Field(
        None, title="Stock Tank Oil Molecular Weight"
    )
    temperature_unit: Literal["C", "K", "F", "R"] | None = Field("C", title="Temperature Unit")
    type: Literal["MSS"] = Field(..., title="Type")


class SlimtubeExperimentModel(BaseModel):
    average_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field("bara", title="Average Pressure Unit")
    final_recovery_unit: Literal["%", "frac."] | None = Field("%", title="Final Recovery Unit")
    injection_gas_composition: CompositionModel | None = None
    name: str = Field(..., title="Name")
    recovery_at_1_2_pore_volumes_injected_unit: Literal["%", "frac."] | None = Field(
        "%", title="Recovery At 1 2 Pore Volumes Injected Unit"
    )
    recovery_at_1_pore_volumes_injected_unit: Literal["%", "frac."] | None = Field(
        "%", title="Recovery At 1 Pore Volumes Injected Unit"
    )
    reported_minimum_miscibility_pressure: float | None = Field(
        None, title="Reported Minimum Miscibility Pressure"
    )
    reported_minimum_miscibility_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Reported Minimum Miscibility Pressure Unit")
    stages: list[SlimtubeStageModel] = Field(..., title="Stages")
    stock_tank_oil_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        "g/cm3", title="Stock Tank Oil Density Unit"
    )
    target_injection_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field("bara", title="Target Injection Pressure Unit")
    target_temperature: float | None = Field(None, title="Target Temperature")
    target_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Target Temperature Unit"
    )
    temperature_unit: Literal["C", "K", "F", "R"] | None = Field("C", title="Temperature Unit")
    type: Literal["Slimtube"] = Field(..., title="Type")


class SwellTestExperimentModel(BaseModel):
    density_at_saturation_pressure_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = (
        Field("g/cm3", title="Density At Saturation Pressure Unit")
    )
    gas_oil_ratio_unit: (
        Literal[
            "Sm3/Sm3",
            "Sm3/m3",
            "scf/STB",
            "scf/bbl",
            "1e6-Sm3/Sm3",
            "1e6-Sm3/m3",
            "MMscf/STB",
            "MMscf/bbl",
            "1e3-Sm3/Sm3",
            "1e3-Sm3/m3",
            "Mscf/STB",
            "Mscf/bbl",
        ]
        | None
    ) = Field("Sm3/Sm3", title="Gas Oil Ratio Unit")
    injection_gas_composition: CompositionModel | None = None
    moles_injected_unit: (
        Literal["inj./total %", "inj./initial %", "inj./total", "inj./initial"] | None
    ) = Field("inj./total %", title="Moles Injected Unit")
    name: str = Field(..., title="Name")
    relative_volume_at_saturation_pressure_unit: Literal["%", "frac."] | None = Field(
        "%", title="Relative Volume At Saturation Pressure Unit"
    )
    saturation_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field("bara", title="Saturation Pressure Unit")
    stage_data: list[SwellTestStageModel] = Field(..., title="Stage Data")
    temperature: float = Field(..., title="Temperature")
    temperature_unit: Literal["C", "K", "F", "R"] = Field(..., title="Temperature Unit")
    type: Literal["SwellTest"] = Field(..., title="Type")


class VISCOExperimentModel(BaseModel):
    gas_viscosity_unit: Literal["cP", "micro-cP"] | None = Field("cP", title="Gas Viscosity Unit")
    name: str = Field(..., title="Name")
    oil_viscosity_unit: Literal["cP", "micro-cP"] | None = Field("cP", title="Oil Viscosity Unit")
    pressure_unit: Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None = (
        Field("bara", title="Pressure Unit")
    )
    stages: list[VISCOStageModel] = Field(..., title="Stages")
    temperature: float = Field(..., title="Temperature")
    temperature_unit: Literal["C", "K", "F", "R"] = Field(..., title="Temperature Unit")
    type: Literal["VISCO"] = Field(..., title="Type")


class CVDExperimentModel(BaseModel):
    cumulative_moles_removed_unit: Literal["%", "frac."] | None = Field(
        "%", title="Cumulative Moles Removed Unit"
    )
    final_stage_oil_composition: CompositionModel | None = None
    final_stage_oil_density: float | None = Field(None, title="Final Stage Oil Density")
    final_stage_oil_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Final Stage Oil Density Unit"
    )
    final_stage_oil_mw: float | None = Field(None, title="Final Stage Oil Mw")
    gas_density_unit: Literal["SG", "kg/m3", "g/cm3", "lbm/bbl", "lbm/ft3"] | None = Field(
        "g/cm3", title="Gas Density Unit"
    )
    gas_viscosity_unit: Literal["cP", "micro-cP"] | None = Field("cP", title="Gas Viscosity Unit")
    incremental_moles_removed_unit: Literal["%", "frac."] | None = Field(
        "%", title="Incremental Moles Removed Unit"
    )
    liberated_gas_compositions: LiberatedGasCompositionsModel | None = None
    name: str = Field(..., title="Name")
    oil_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        "g/cm3", title="Oil Density Unit"
    )
    pressure_unit: Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None = (
        Field("bara", title="Pressure Unit")
    )
    relative_oil_volume_unit: Literal["%", "frac."] | None = Field(
        "%", title="Relative Oil Volume Unit"
    )
    saturation_pressure_type: Literal["Dewpoint", "Bubblepoint"] = Field(
        ..., title="Saturation Pressure Type"
    )
    stages: list[CVDStageModel] = Field(..., title="Stages")
    stock_tank_oil_density: float | None = Field(None, title="Stock Tank Oil Density")
    stock_tank_oil_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Stock Tank Oil Density Unit"
    )
    temperature: float = Field(..., title="Temperature")
    temperature_unit: Literal["C", "K", "F", "R"] = Field(..., title="Temperature Unit")
    type: Literal["CVD"] = Field(..., title="Type")


class DLEExperimentModel(BaseModel):
    average_residual_oil_density: float | None = Field(None, title="Average Residual Oil Density")
    average_residual_oil_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = (
        Field(None, title="Average Residual Oil Density Unit")
    )
    average_residual_oil_mw: float | None = Field(None, title="Average Residual Oil Mw")
    dle_experiment_type: Literal["Standard DLE Experiment", "High Pressure Final Stage"] = Field(
        ..., title="Dle Experiment Type"
    )
    evolved_gas_composition: CompositionModel | None = None
    evolved_gas_specific_gravity: float | None = Field(None, title="Evolved Gas Specific Gravity")
    gas_density_unit: Literal["SG", "kg/m3", "g/cm3", "lbm/bbl", "lbm/ft3"] | None = Field(
        "g/cm3", title="Gas Density Unit"
    )
    gas_viscosity_unit: Literal["cP", "micro-cP"] | None = Field("cP", title="Gas Viscosity Unit")
    gor_unit: (
        Literal["Sm3/Sm3", "scf/STB", "1e6-Sm3/Sm3", "MMscf/STB", "1e3-Sm3/Sm3", "Mscf/STB"] | None
    ) = Field("Sm3/Sm3", title="Gor Unit")
    liberated_gas_compositions: LiberatedGasCompositionsModel | None = None
    liberated_gas_unit: (
        Literal[
            "Sm3/Sm3",
            "Sm3/m3",
            "scf/STB",
            "scf/bbl",
            "1e6-Sm3/Sm3",
            "1e6-Sm3/m3",
            "MMscf/STB",
            "MMscf/bbl",
            "1e3-Sm3/Sm3",
            "1e3-Sm3/m3",
            "Mscf/STB",
            "Mscf/bbl",
        ]
        | None
    ) = Field("Sm3/Sm3", title="Liberated Gas Unit")
    name: str = Field(..., title="Name")
    oil_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        "g/cm3", title="Oil Density Unit"
    )
    oil_fvf_unit: Literal["m3/Sm3", "bbl/STB"] | None = Field("m3/Sm3", title="Oil Fvf Unit")
    pressure_unit: Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None = (
        Field("bara", title="Pressure Unit")
    )
    residual_oil_composition: CompositionModel | None = None
    saturation_pressure_type: Literal["Dewpoint", "Bubblepoint"] = Field(
        ..., title="Saturation Pressure Type"
    )
    stages: list[DLEStageModel] = Field(..., title="Stages")
    temperature: float = Field(..., title="Temperature")
    temperature_unit: Literal["C", "K", "F", "R"] = Field(..., title="Temperature Unit")
    type: Literal["DLE"] = Field(..., title="Type")


class Experiments(
    RootModel[
        CCEExperimentModel
        | CVDExperimentModel
        | DLEExperimentModel
        | MSSExperimentModel
        | TBPExperimentModel
        | VISCOExperimentModel
        | SlimtubeExperimentModel
        | SwellTestExperimentModel
    ]
):
    root: (
        CCEExperimentModel
        | CVDExperimentModel
        | DLEExperimentModel
        | MSSExperimentModel
        | TBPExperimentModel
        | VISCOExperimentModel
        | SlimtubeExperimentModel
        | SwellTestExperimentModel
    ) = Field(..., discriminator="type")


class ExternalCreateSampleModel(BaseModel):
    bottom_perforation_depth: float | None = Field(None, title="Bottom Perforation Depth")
    bottom_perforation_depth_unit: Literal["m", "ft"] | None = Field(
        None, title="Bottom Perforation Depth Unit"
    )
    drained_water_density: float | None = Field(None, title="Drained Water Density")
    drained_water_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Drained Water Density Unit"
    )
    drawdown_pressure: float | None = Field(None, title="Drawdown Pressure")
    drawdown_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Drawdown Pressure Unit")
    experiments: list[Experiments] | None = Field(None, title="Experiments")
    flashed_gas_composition: CompositionModel | None = Field(None, title="Flashed Gas Composition")
    flashed_gas_mw: float | None = Field(None, title="Flashed Gas Mw")
    flashed_gas_specific_gravity: float | None = Field(None, title="Flashed Gas Specific Gravity")
    flashed_oil_composition: CompositionModel | None = Field(None, title="Flashed Oil Composition")
    flashed_oil_contamination: float | None = Field(None, title="Flashed Oil Contamination")
    flashed_oil_contamination_unit: Literal["mass%", "mole%"] | None = Field(
        None, title="Flashed Oil Contamination Unit"
    )
    flashed_oil_density: float | None = Field(None, title="Flashed Oil Density")
    flashed_oil_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Flashed Oil Density Unit"
    )
    flashed_oil_mw: float | None = Field(None, title="Flashed Oil Mw")
    flashed_oil_temperature: float | None = Field(None, title="Flashed Oil Temperature")
    flashed_oil_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Flashed Oil Temperature Unit"
    )
    fluid_type: Literal["Water", "Gas", "Oil", "Mud", "Multiphase"] = Field(..., title="Fluid Type")
    gas_composition: CompositionModel | None = Field(None, title="Gas Composition")
    gas_specific_gravity: float | None = Field(None, title="Gas Specific Gravity")
    gas_water_ratio: float | None = Field(None, title="Gas Water Ratio")
    gas_water_ratio_unit: (
        Literal[
            "Sm3/Sm3",
            "Sm3/m3",
            "scf/STB",
            "scf/bbl",
            "1e6-Sm3/Sm3",
            "1e6-Sm3/m3",
            "MMscf/STB",
            "MMscf/bbl",
            "1e3-Sm3/Sm3",
            "1e3-Sm3/m3",
            "Mscf/STB",
            "Mscf/bbl",
        ]
        | None
    ) = Field(None, title="Gas Water Ratio Unit")
    id: int | None = Field(None, title="Id")
    ions: list[ExternalIonDataModel] | None = Field(None, title="Ions")
    location: Any = Field(None, title="Location")
    measured_depth: float | None = Field(None, title="Measured Depth")
    measured_depth_unit: Literal["m", "ft"] | None = Field(None, title="Measured Depth Unit")
    mud_base: Literal["Water", "Oil"] | None = Field(None, title="Mud Base")
    mud_sample_id: int | None = Field(None, title="Mud Sample Id")
    name: str = Field(..., title="Name")
    obm_composition: CompositionModel | None = Field(None, title="Obm Composition")
    obm_density: float | None = Field(None, title="Obm Density")
    obm_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Obm Density Unit"
    )
    obm_mw: float | None = Field(None, title="Obm Mw")
    pressure_at_lab: float | None = Field(None, title="Pressure At Lab")
    pressure_at_lab_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Pressure At Lab Unit")
    pressure_when_sampled: float | None = Field(None, title="Pressure When Sampled")
    pressure_when_sampled_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Pressure When Sampled Unit")
    recombined_fluid_composition: CompositionModel | None = Field(
        None, title="Recombined Fluid Composition"
    )
    recombined_fluid_contamination: float | None = Field(
        None, title="Recombined Fluid Contamination"
    )
    recombined_fluid_contamination_unit: Literal["mass%", "mole%"] | None = Field(
        None, title="Recombined Fluid Contamination Unit"
    )
    recombined_fluid_gor: float | None = Field(None, title="Recombined Fluid Gor")
    recombined_fluid_gor_unit: (
        Literal[
            "Sm3/Sm3",
            "Sm3/m3",
            "scf/STB",
            "scf/bbl",
            "1e6-Sm3/Sm3",
            "1e6-Sm3/m3",
            "MMscf/STB",
            "MMscf/bbl",
            "1e3-Sm3/Sm3",
            "1e3-Sm3/m3",
            "Mscf/STB",
            "Mscf/bbl",
        ]
        | None
    ) = Field(None, title="Recombined Fluid Gor Unit")
    recombined_fluid_mw: float | None = Field(None, title="Recombined Fluid Mw")
    reservoir_pressure: float | None = Field(None, title="Reservoir Pressure")
    reservoir_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Reservoir Pressure Unit")
    reservoir_temperature: float | None = Field(None, title="Reservoir Temperature")
    reservoir_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Reservoir Temperature Unit"
    )
    sampling_date: date | None = Field(None, title="Sampling Date")
    sep_gas_composition: CompositionModel | None = Field(None, title="Sep Gas Composition")
    sep_gas_mw: float | None = Field(None, title="Sep Gas Mw")
    sep_gor: float | None = Field(None, title="Sep Gor")
    sep_gor_unit: (
        Literal[
            "Sm3/Sm3",
            "Sm3/m3",
            "scf/STB",
            "scf/bbl",
            "1e6-Sm3/Sm3",
            "1e6-Sm3/m3",
            "MMscf/STB",
            "MMscf/bbl",
            "1e3-Sm3/Sm3",
            "1e3-Sm3/m3",
            "Mscf/STB",
            "Mscf/bbl",
        ]
        | None
    ) = Field(None, title="Sep Gor Unit")
    sep_oil_composition: CompositionModel | None = Field(None, title="Sep Oil Composition")
    sep_oil_density: float | None = Field(None, title="Sep Oil Density")
    sep_oil_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Sep Oil Density Unit"
    )
    sep_oil_mw: float | None = Field(None, title="Sep Oil Mw")
    sep_pressure: float | None = Field(None, title="Sep Pressure")
    sep_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Sep Pressure Unit")
    sep_temperature: float | None = Field(None, title="Sep Temperature")
    sep_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Sep Temperature Unit"
    )
    temperature_at_lab: float | None = Field(None, title="Temperature At Lab")
    temperature_at_lab_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Temperature At Lab Unit"
    )
    temperature_when_sampled: float | None = Field(None, title="Temperature When Sampled")
    temperature_when_sampled_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Temperature When Sampled Unit"
    )
    top_perforation_depth: float | None = Field(None, title="Top Perforation Depth")
    top_perforation_depth_unit: Literal["m", "ft"] | None = Field(
        None, title="Top Perforation Depth Unit"
    )
    transfer_pressure: float | None = Field(None, title="Transfer Pressure")
    transfer_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Transfer Pressure Unit")
    transfer_temperature: float | None = Field(None, title="Transfer Temperature")
    transfer_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Transfer Temperature Unit"
    )
    true_vertical_depth: float | None = Field(None, title="True Vertical Depth")
    true_vertical_depth_unit: Literal["m", "ft"] | None = Field(
        None, title="True Vertical Depth Unit"
    )
    type: Literal["REC", "SEP", "BHS", "OFT", "SEPO", "SEPG", "OBM", "GAS", "FLO", "WATER"] = Field(
        ..., title="Type"
    )
    water_conductivity: float | None = Field(None, title="Water Conductivity")
    water_conductivity_unit: Literal["micro-S/cm"] | None = Field(
        None, title="Water Conductivity Unit"
    )
    water_ph: float | None = Field(None, title="Water Ph")
    water_resistivity: float | None = Field(None, title="Water Resistivity")
    water_resistivity_unit: Literal["ohm-m"] | None = Field(None, title="Water Resistivity Unit")
    water_temperature: float | None = Field(None, title="Water Temperature")
    water_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Water Temperature Unit"
    )
    well_id: int = Field(..., title="Well Id")


class ExternalCreateWellSampleModel(BaseModel):
    bottom_perforation_depth: float | None = Field(None, title="Bottom Perforation Depth")
    bottom_perforation_depth_unit: Literal["m", "ft"] | None = Field(
        None, title="Bottom Perforation Depth Unit"
    )
    drained_water_density: float | None = Field(None, title="Drained Water Density")
    drained_water_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Drained Water Density Unit"
    )
    drawdown_pressure: float | None = Field(None, title="Drawdown Pressure")
    drawdown_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Drawdown Pressure Unit")
    experiments: list[Experiments] | None = Field(None, title="Experiments")
    flashed_gas_composition: CompositionModel | None = Field(None, title="Flashed Gas Composition")
    flashed_gas_mw: float | None = Field(None, title="Flashed Gas Mw")
    flashed_gas_specific_gravity: float | None = Field(None, title="Flashed Gas Specific Gravity")
    flashed_oil_composition: CompositionModel | None = Field(None, title="Flashed Oil Composition")
    flashed_oil_contamination: float | None = Field(None, title="Flashed Oil Contamination")
    flashed_oil_contamination_unit: Literal["mass%", "mole%"] | None = Field(
        None, title="Flashed Oil Contamination Unit"
    )
    flashed_oil_density: float | None = Field(None, title="Flashed Oil Density")
    flashed_oil_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Flashed Oil Density Unit"
    )
    flashed_oil_mw: float | None = Field(None, title="Flashed Oil Mw")
    flashed_oil_temperature: float | None = Field(None, title="Flashed Oil Temperature")
    flashed_oil_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Flashed Oil Temperature Unit"
    )
    fluid_type: Literal["Water", "Gas", "Oil", "Mud", "Multiphase"] = Field(..., title="Fluid Type")
    gas_composition: CompositionModel | None = Field(None, title="Gas Composition")
    gas_specific_gravity: float | None = Field(None, title="Gas Specific Gravity")
    gas_water_ratio: float | None = Field(None, title="Gas Water Ratio")
    gas_water_ratio_unit: (
        Literal[
            "Sm3/Sm3",
            "Sm3/m3",
            "scf/STB",
            "scf/bbl",
            "1e6-Sm3/Sm3",
            "1e6-Sm3/m3",
            "MMscf/STB",
            "MMscf/bbl",
            "1e3-Sm3/Sm3",
            "1e3-Sm3/m3",
            "Mscf/STB",
            "Mscf/bbl",
        ]
        | None
    ) = Field(None, title="Gas Water Ratio Unit")
    id: int | None = Field(None, title="Id")
    ions: list[ExternalIonDataModel] | None = Field(None, title="Ions")
    location: Any = Field(None, title="Location")
    measured_depth: float | None = Field(None, title="Measured Depth")
    measured_depth_unit: Literal["m", "ft"] | None = Field(None, title="Measured Depth Unit")
    mud_base: Literal["Water", "Oil"] | None = Field(None, title="Mud Base")
    mud_sample_id: int | None = Field(None, title="Mud Sample Id")
    name: str = Field(..., title="Name")
    obm_composition: CompositionModel | None = Field(None, title="Obm Composition")
    obm_density: float | None = Field(None, title="Obm Density")
    obm_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Obm Density Unit"
    )
    obm_mw: float | None = Field(None, title="Obm Mw")
    pressure_at_lab: float | None = Field(None, title="Pressure At Lab")
    pressure_at_lab_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Pressure At Lab Unit")
    pressure_when_sampled: float | None = Field(None, title="Pressure When Sampled")
    pressure_when_sampled_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Pressure When Sampled Unit")
    recombined_fluid_composition: CompositionModel | None = Field(
        None, title="Recombined Fluid Composition"
    )
    recombined_fluid_contamination: float | None = Field(
        None, title="Recombined Fluid Contamination"
    )
    recombined_fluid_contamination_unit: Literal["mass%", "mole%"] | None = Field(
        None, title="Recombined Fluid Contamination Unit"
    )
    recombined_fluid_gor: float | None = Field(None, title="Recombined Fluid Gor")
    recombined_fluid_gor_unit: (
        Literal[
            "Sm3/Sm3",
            "Sm3/m3",
            "scf/STB",
            "scf/bbl",
            "1e6-Sm3/Sm3",
            "1e6-Sm3/m3",
            "MMscf/STB",
            "MMscf/bbl",
            "1e3-Sm3/Sm3",
            "1e3-Sm3/m3",
            "Mscf/STB",
            "Mscf/bbl",
        ]
        | None
    ) = Field(None, title="Recombined Fluid Gor Unit")
    recombined_fluid_mw: float | None = Field(None, title="Recombined Fluid Mw")
    reservoir_pressure: float | None = Field(None, title="Reservoir Pressure")
    reservoir_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Reservoir Pressure Unit")
    reservoir_temperature: float | None = Field(None, title="Reservoir Temperature")
    reservoir_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Reservoir Temperature Unit"
    )
    sampling_date: date | None = Field(None, title="Sampling Date")
    sep_gas_composition: CompositionModel | None = Field(None, title="Sep Gas Composition")
    sep_gas_mw: float | None = Field(None, title="Sep Gas Mw")
    sep_gor: float | None = Field(None, title="Sep Gor")
    sep_gor_unit: (
        Literal[
            "Sm3/Sm3",
            "Sm3/m3",
            "scf/STB",
            "scf/bbl",
            "1e6-Sm3/Sm3",
            "1e6-Sm3/m3",
            "MMscf/STB",
            "MMscf/bbl",
            "1e3-Sm3/Sm3",
            "1e3-Sm3/m3",
            "Mscf/STB",
            "Mscf/bbl",
        ]
        | None
    ) = Field(None, title="Sep Gor Unit")
    sep_oil_composition: CompositionModel | None = Field(None, title="Sep Oil Composition")
    sep_oil_density: float | None = Field(None, title="Sep Oil Density")
    sep_oil_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Sep Oil Density Unit"
    )
    sep_oil_mw: float | None = Field(None, title="Sep Oil Mw")
    sep_pressure: float | None = Field(None, title="Sep Pressure")
    sep_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Sep Pressure Unit")
    sep_temperature: float | None = Field(None, title="Sep Temperature")
    sep_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Sep Temperature Unit"
    )
    temperature_at_lab: float | None = Field(None, title="Temperature At Lab")
    temperature_at_lab_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Temperature At Lab Unit"
    )
    temperature_when_sampled: float | None = Field(None, title="Temperature When Sampled")
    temperature_when_sampled_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Temperature When Sampled Unit"
    )
    top_perforation_depth: float | None = Field(None, title="Top Perforation Depth")
    top_perforation_depth_unit: Literal["m", "ft"] | None = Field(
        None, title="Top Perforation Depth Unit"
    )
    transfer_pressure: float | None = Field(None, title="Transfer Pressure")
    transfer_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Transfer Pressure Unit")
    transfer_temperature: float | None = Field(None, title="Transfer Temperature")
    transfer_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Transfer Temperature Unit"
    )
    true_vertical_depth: float | None = Field(None, title="True Vertical Depth")
    true_vertical_depth_unit: Literal["m", "ft"] | None = Field(
        None, title="True Vertical Depth Unit"
    )
    type: Literal["REC", "SEP", "BHS", "OFT", "SEPO", "SEPG", "OBM", "GAS", "FLO", "WATER"] = Field(
        ..., title="Type"
    )
    water_conductivity: float | None = Field(None, title="Water Conductivity")
    water_conductivity_unit: Literal["micro-S/cm"] | None = Field(
        None, title="Water Conductivity Unit"
    )
    water_ph: float | None = Field(None, title="Water Ph")
    water_resistivity: float | None = Field(None, title="Water Resistivity")
    water_resistivity_unit: Literal["ohm-m"] | None = Field(None, title="Water Resistivity Unit")
    water_temperature: float | None = Field(None, title="Water Temperature")
    water_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Water Temperature Unit"
    )
    well_id: int | None = Field(None, title="Well Id")


class ExternalGetSampleModel(BaseModel):
    bottom_perforation_depth: float | None = Field(None, title="Bottom Perforation Depth")
    bottom_perforation_depth_unit: Literal["m", "ft"] | None = Field(
        None, title="Bottom Perforation Depth Unit"
    )
    drained_water_density: float | None = Field(None, title="Drained Water Density")
    drained_water_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Drained Water Density Unit"
    )
    drawdown_pressure: float | None = Field(None, title="Drawdown Pressure")
    drawdown_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Drawdown Pressure Unit")
    experiments: list[Experiments] | None = Field(None, title="Experiments")
    flashed_gas_composition: CompositionModel | None = Field(None, title="Flashed Gas Composition")
    flashed_gas_mw: float | None = Field(None, title="Flashed Gas Mw")
    flashed_gas_specific_gravity: float | None = Field(None, title="Flashed Gas Specific Gravity")
    flashed_oil_composition: CompositionModel | None = Field(None, title="Flashed Oil Composition")
    flashed_oil_contamination: float | None = Field(None, title="Flashed Oil Contamination")
    flashed_oil_contamination_unit: Literal["mass%", "mole%"] | None = Field(
        None, title="Flashed Oil Contamination Unit"
    )
    flashed_oil_density: float | None = Field(None, title="Flashed Oil Density")
    flashed_oil_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Flashed Oil Density Unit"
    )
    flashed_oil_mw: float | None = Field(None, title="Flashed Oil Mw")
    flashed_oil_temperature: float | None = Field(None, title="Flashed Oil Temperature")
    flashed_oil_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Flashed Oil Temperature Unit"
    )
    fluid_type: Literal["Water", "Gas", "Oil", "Mud", "Multiphase"] | None = Field(
        None, title="Fluid Type"
    )
    gas_composition: CompositionModel | None = Field(None, title="Gas Composition")
    gas_specific_gravity: float | None = Field(None, title="Gas Specific Gravity")
    gas_water_ratio: float | None = Field(None, title="Gas Water Ratio")
    gas_water_ratio_unit: (
        Literal[
            "Sm3/Sm3",
            "Sm3/m3",
            "scf/STB",
            "scf/bbl",
            "1e6-Sm3/Sm3",
            "1e6-Sm3/m3",
            "MMscf/STB",
            "MMscf/bbl",
            "1e3-Sm3/Sm3",
            "1e3-Sm3/m3",
            "Mscf/STB",
            "Mscf/bbl",
        ]
        | None
    ) = Field(None, title="Gas Water Ratio Unit")
    id: int | None = Field(None, title="Id")
    ions: list[ExternalIonDataModel] | None = Field(None, title="Ions")
    location: Any = Field(None, title="Location")
    measured_depth: float | None = Field(None, title="Measured Depth")
    measured_depth_unit: Literal["m", "ft"] | None = Field(None, title="Measured Depth Unit")
    mud_base: Literal["Water", "Oil"] | None = Field(None, title="Mud Base")
    mud_sample_id: int | None = Field(None, title="Mud Sample Id")
    name: str | None = Field(None, title="Name")
    obm_composition: CompositionModel | None = Field(None, title="Obm Composition")
    obm_density: float | None = Field(None, title="Obm Density")
    obm_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Obm Density Unit"
    )
    obm_mw: float | None = Field(None, title="Obm Mw")
    pressure_at_lab: float | None = Field(None, title="Pressure At Lab")
    pressure_at_lab_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Pressure At Lab Unit")
    pressure_when_sampled: float | None = Field(None, title="Pressure When Sampled")
    pressure_when_sampled_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Pressure When Sampled Unit")
    recombined_fluid_composition: CompositionModel | None = Field(
        None, title="Recombined Fluid Composition"
    )
    recombined_fluid_contamination: float | None = Field(
        None, title="Recombined Fluid Contamination"
    )
    recombined_fluid_contamination_unit: Literal["mass%", "mole%"] | None = Field(
        None, title="Recombined Fluid Contamination Unit"
    )
    recombined_fluid_gor: float | None = Field(None, title="Recombined Fluid Gor")
    recombined_fluid_gor_unit: (
        Literal[
            "Sm3/Sm3",
            "Sm3/m3",
            "scf/STB",
            "scf/bbl",
            "1e6-Sm3/Sm3",
            "1e6-Sm3/m3",
            "MMscf/STB",
            "MMscf/bbl",
            "1e3-Sm3/Sm3",
            "1e3-Sm3/m3",
            "Mscf/STB",
            "Mscf/bbl",
        ]
        | None
    ) = Field(None, title="Recombined Fluid Gor Unit")
    recombined_fluid_mw: float | None = Field(None, title="Recombined Fluid Mw")
    reservoir_pressure: float | None = Field(None, title="Reservoir Pressure")
    reservoir_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Reservoir Pressure Unit")
    reservoir_temperature: float | None = Field(None, title="Reservoir Temperature")
    reservoir_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Reservoir Temperature Unit"
    )
    sampling_date: date | None = Field(None, title="Sampling Date")
    sep_gas_composition: CompositionModel | None = Field(None, title="Sep Gas Composition")
    sep_gas_mw: float | None = Field(None, title="Sep Gas Mw")
    sep_gor: float | None = Field(None, title="Sep Gor")
    sep_gor_unit: (
        Literal[
            "Sm3/Sm3",
            "Sm3/m3",
            "scf/STB",
            "scf/bbl",
            "1e6-Sm3/Sm3",
            "1e6-Sm3/m3",
            "MMscf/STB",
            "MMscf/bbl",
            "1e3-Sm3/Sm3",
            "1e3-Sm3/m3",
            "Mscf/STB",
            "Mscf/bbl",
        ]
        | None
    ) = Field(None, title="Sep Gor Unit")
    sep_oil_composition: CompositionModel | None = Field(None, title="Sep Oil Composition")
    sep_oil_density: float | None = Field(None, title="Sep Oil Density")
    sep_oil_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Sep Oil Density Unit"
    )
    sep_oil_mw: float | None = Field(None, title="Sep Oil Mw")
    sep_pressure: float | None = Field(None, title="Sep Pressure")
    sep_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Sep Pressure Unit")
    sep_temperature: float | None = Field(None, title="Sep Temperature")
    sep_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Sep Temperature Unit"
    )
    temperature_at_lab: float | None = Field(None, title="Temperature At Lab")
    temperature_at_lab_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Temperature At Lab Unit"
    )
    temperature_when_sampled: float | None = Field(None, title="Temperature When Sampled")
    temperature_when_sampled_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Temperature When Sampled Unit"
    )
    top_perforation_depth: float | None = Field(None, title="Top Perforation Depth")
    top_perforation_depth_unit: Literal["m", "ft"] | None = Field(
        None, title="Top Perforation Depth Unit"
    )
    transfer_pressure: float | None = Field(None, title="Transfer Pressure")
    transfer_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Transfer Pressure Unit")
    transfer_temperature: float | None = Field(None, title="Transfer Temperature")
    transfer_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Transfer Temperature Unit"
    )
    true_vertical_depth: float | None = Field(None, title="True Vertical Depth")
    true_vertical_depth_unit: Literal["m", "ft"] | None = Field(
        None, title="True Vertical Depth Unit"
    )
    type: (
        Literal["REC", "SEP", "BHS", "OFT", "SEPO", "SEPG", "OBM", "GAS", "FLO", "WATER"] | None
    ) = Field(None, title="Type")
    water_conductivity: float | None = Field(None, title="Water Conductivity")
    water_conductivity_unit: Literal["micro-S/cm"] | None = Field(
        None, title="Water Conductivity Unit"
    )
    water_ph: float | None = Field(None, title="Water Ph")
    water_resistivity: float | None = Field(None, title="Water Resistivity")
    water_resistivity_unit: Literal["ohm-m"] | None = Field(None, title="Water Resistivity Unit")
    water_temperature: float | None = Field(None, title="Water Temperature")
    water_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Water Temperature Unit"
    )
    well_id: int | None = Field(None, title="Well Id")


class ExternalGetWellModel(BaseModel):
    basin_id: float | None = Field(None, title="Basin Id")
    basin_name: str | None = Field(..., title="Basin Name")
    field_id: float | None = Field(None, title="Field Id")
    field_name: str | None = Field(..., title="Field Name")
    field_segment_id: float | None = Field(None, title="Field Segment Id")
    field_segment_name: str | None = Field(..., title="Field Segment Name")
    formation_id: float | None = Field(None, title="Formation Id")
    formation_name: str | None = Field(..., title="Formation Name")
    formation_zone_id: float | None = Field(None, title="Formation Zone Id")
    formation_zone_name: str | None = Field(..., title="Formation Zone Name")
    id: int | None = Field(None, title="Id")
    location: Any = Field(None, title="Location")
    name: str | None = Field(None, title="Name")
    region_id: int | None = Field(None, title="Region Id")
    samples: list[ExternalGetSampleModel] = Field(..., title="Samples")
    sub_basin_id: float | None = Field(None, title="Sub Basin Id")
    sub_basin_name: str | None = Field(..., title="Sub Basin Name")
    uwi: str | None = Field(None, title="Uwi")


class ExternalUpdateSampleItemModel(BaseModel):
    bottom_perforation_depth: float | None = Field(None, title="Bottom Perforation Depth")
    bottom_perforation_depth_unit: Literal["m", "ft"] | None = Field(
        None, title="Bottom Perforation Depth Unit"
    )
    drained_water_density: float | None = Field(None, title="Drained Water Density")
    drained_water_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Drained Water Density Unit"
    )
    drawdown_pressure: float | None = Field(None, title="Drawdown Pressure")
    drawdown_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Drawdown Pressure Unit")
    experiments: list[Experiments] | None = Field(None, title="Experiments")
    flashed_gas_composition: CompositionModel | None = Field(None, title="Flashed Gas Composition")
    flashed_gas_mw: float | None = Field(None, title="Flashed Gas Mw")
    flashed_gas_specific_gravity: float | None = Field(None, title="Flashed Gas Specific Gravity")
    flashed_oil_composition: CompositionModel | None = Field(None, title="Flashed Oil Composition")
    flashed_oil_contamination: float | None = Field(None, title="Flashed Oil Contamination")
    flashed_oil_contamination_unit: Literal["mass%", "mole%"] | None = Field(
        None, title="Flashed Oil Contamination Unit"
    )
    flashed_oil_density: float | None = Field(None, title="Flashed Oil Density")
    flashed_oil_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Flashed Oil Density Unit"
    )
    flashed_oil_mw: float | None = Field(None, title="Flashed Oil Mw")
    flashed_oil_temperature: float | None = Field(None, title="Flashed Oil Temperature")
    flashed_oil_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Flashed Oil Temperature Unit"
    )
    fluid_type: Literal["Water", "Gas", "Oil", "Mud", "Multiphase"] | None = Field(
        None, title="Fluid Type"
    )
    gas_composition: CompositionModel | None = Field(None, title="Gas Composition")
    gas_specific_gravity: float | None = Field(None, title="Gas Specific Gravity")
    gas_water_ratio: float | None = Field(None, title="Gas Water Ratio")
    gas_water_ratio_unit: (
        Literal[
            "Sm3/Sm3",
            "Sm3/m3",
            "scf/STB",
            "scf/bbl",
            "1e6-Sm3/Sm3",
            "1e6-Sm3/m3",
            "MMscf/STB",
            "MMscf/bbl",
            "1e3-Sm3/Sm3",
            "1e3-Sm3/m3",
            "Mscf/STB",
            "Mscf/bbl",
        ]
        | None
    ) = Field(None, title="Gas Water Ratio Unit")
    id: int = Field(..., title="Id")
    ions: list[ExternalIonDataModel] | None = Field(None, title="Ions")
    location: Any = Field(None, title="Location")
    measured_depth: float | None = Field(None, title="Measured Depth")
    measured_depth_unit: Literal["m", "ft"] | None = Field(None, title="Measured Depth Unit")
    mud_base: Literal["Water", "Oil"] | None = Field(None, title="Mud Base")
    mud_sample_id: int | None = Field(None, title="Mud Sample Id")
    name: str | None = Field(None, title="Name")
    obm_composition: CompositionModel | None = Field(None, title="Obm Composition")
    obm_density: float | None = Field(None, title="Obm Density")
    obm_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Obm Density Unit"
    )
    obm_mw: float | None = Field(None, title="Obm Mw")
    pressure_at_lab: float | None = Field(None, title="Pressure At Lab")
    pressure_at_lab_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Pressure At Lab Unit")
    pressure_when_sampled: float | None = Field(None, title="Pressure When Sampled")
    pressure_when_sampled_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Pressure When Sampled Unit")
    recombined_fluid_composition: CompositionModel | None = Field(
        None, title="Recombined Fluid Composition"
    )
    recombined_fluid_contamination: float | None = Field(
        None, title="Recombined Fluid Contamination"
    )
    recombined_fluid_contamination_unit: Literal["mass%", "mole%"] | None = Field(
        None, title="Recombined Fluid Contamination Unit"
    )
    recombined_fluid_gor: float | None = Field(None, title="Recombined Fluid Gor")
    recombined_fluid_gor_unit: (
        Literal[
            "Sm3/Sm3",
            "Sm3/m3",
            "scf/STB",
            "scf/bbl",
            "1e6-Sm3/Sm3",
            "1e6-Sm3/m3",
            "MMscf/STB",
            "MMscf/bbl",
            "1e3-Sm3/Sm3",
            "1e3-Sm3/m3",
            "Mscf/STB",
            "Mscf/bbl",
        ]
        | None
    ) = Field(None, title="Recombined Fluid Gor Unit")
    recombined_fluid_mw: float | None = Field(None, title="Recombined Fluid Mw")
    reservoir_pressure: float | None = Field(None, title="Reservoir Pressure")
    reservoir_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Reservoir Pressure Unit")
    reservoir_temperature: float | None = Field(None, title="Reservoir Temperature")
    reservoir_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Reservoir Temperature Unit"
    )
    sampling_date: date | None = Field(None, title="Sampling Date")
    sep_gas_composition: CompositionModel | None = Field(None, title="Sep Gas Composition")
    sep_gas_mw: float | None = Field(None, title="Sep Gas Mw")
    sep_gor: float | None = Field(None, title="Sep Gor")
    sep_gor_unit: (
        Literal[
            "Sm3/Sm3",
            "Sm3/m3",
            "scf/STB",
            "scf/bbl",
            "1e6-Sm3/Sm3",
            "1e6-Sm3/m3",
            "MMscf/STB",
            "MMscf/bbl",
            "1e3-Sm3/Sm3",
            "1e3-Sm3/m3",
            "Mscf/STB",
            "Mscf/bbl",
        ]
        | None
    ) = Field(None, title="Sep Gor Unit")
    sep_oil_composition: CompositionModel | None = Field(None, title="Sep Oil Composition")
    sep_oil_density: float | None = Field(None, title="Sep Oil Density")
    sep_oil_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Sep Oil Density Unit"
    )
    sep_oil_mw: float | None = Field(None, title="Sep Oil Mw")
    sep_pressure: float | None = Field(None, title="Sep Pressure")
    sep_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Sep Pressure Unit")
    sep_temperature: float | None = Field(None, title="Sep Temperature")
    sep_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Sep Temperature Unit"
    )
    temperature_at_lab: float | None = Field(None, title="Temperature At Lab")
    temperature_at_lab_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Temperature At Lab Unit"
    )
    temperature_when_sampled: float | None = Field(None, title="Temperature When Sampled")
    temperature_when_sampled_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Temperature When Sampled Unit"
    )
    top_perforation_depth: float | None = Field(None, title="Top Perforation Depth")
    top_perforation_depth_unit: Literal["m", "ft"] | None = Field(
        None, title="Top Perforation Depth Unit"
    )
    transfer_pressure: float | None = Field(None, title="Transfer Pressure")
    transfer_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Transfer Pressure Unit")
    transfer_temperature: float | None = Field(None, title="Transfer Temperature")
    transfer_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Transfer Temperature Unit"
    )
    true_vertical_depth: float | None = Field(None, title="True Vertical Depth")
    true_vertical_depth_unit: Literal["m", "ft"] | None = Field(
        None, title="True Vertical Depth Unit"
    )
    type: (
        Literal["REC", "SEP", "BHS", "OFT", "SEPO", "SEPG", "OBM", "GAS", "FLO", "WATER"] | None
    ) = Field(None, title="Type")
    water_conductivity: float | None = Field(None, title="Water Conductivity")
    water_conductivity_unit: Literal["micro-S/cm"] | None = Field(
        None, title="Water Conductivity Unit"
    )
    water_ph: float | None = Field(None, title="Water Ph")
    water_resistivity: float | None = Field(None, title="Water Resistivity")
    water_resistivity_unit: Literal["ohm-m"] | None = Field(None, title="Water Resistivity Unit")
    water_temperature: float | None = Field(None, title="Water Temperature")
    water_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Water Temperature Unit"
    )
    well_id: int | None = Field(None, title="Well Id")


class ExternalUpdateSampleListModel(RootModel[list[ExternalUpdateSampleItemModel]]):
    root: list[ExternalUpdateSampleItemModel] = Field(..., title="UpdateSampleListModel")


class ExternalUpdateSampleModel(BaseModel):
    bottom_perforation_depth: float | None = Field(None, title="Bottom Perforation Depth")
    bottom_perforation_depth_unit: Literal["m", "ft"] | None = Field(
        None, title="Bottom Perforation Depth Unit"
    )
    drained_water_density: float | None = Field(None, title="Drained Water Density")
    drained_water_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Drained Water Density Unit"
    )
    drawdown_pressure: float | None = Field(None, title="Drawdown Pressure")
    drawdown_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Drawdown Pressure Unit")
    experiments: list[Experiments] | None = Field(None, title="Experiments")
    flashed_gas_composition: CompositionModel | None = Field(None, title="Flashed Gas Composition")
    flashed_gas_mw: float | None = Field(None, title="Flashed Gas Mw")
    flashed_gas_specific_gravity: float | None = Field(None, title="Flashed Gas Specific Gravity")
    flashed_oil_composition: CompositionModel | None = Field(None, title="Flashed Oil Composition")
    flashed_oil_contamination: float | None = Field(None, title="Flashed Oil Contamination")
    flashed_oil_contamination_unit: Literal["mass%", "mole%"] | None = Field(
        None, title="Flashed Oil Contamination Unit"
    )
    flashed_oil_density: float | None = Field(None, title="Flashed Oil Density")
    flashed_oil_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Flashed Oil Density Unit"
    )
    flashed_oil_mw: float | None = Field(None, title="Flashed Oil Mw")
    flashed_oil_temperature: float | None = Field(None, title="Flashed Oil Temperature")
    flashed_oil_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Flashed Oil Temperature Unit"
    )
    fluid_type: Literal["Water", "Gas", "Oil", "Mud", "Multiphase"] | None = Field(
        None, title="Fluid Type"
    )
    gas_composition: CompositionModel | None = Field(None, title="Gas Composition")
    gas_specific_gravity: float | None = Field(None, title="Gas Specific Gravity")
    gas_water_ratio: float | None = Field(None, title="Gas Water Ratio")
    gas_water_ratio_unit: (
        Literal[
            "Sm3/Sm3",
            "Sm3/m3",
            "scf/STB",
            "scf/bbl",
            "1e6-Sm3/Sm3",
            "1e6-Sm3/m3",
            "MMscf/STB",
            "MMscf/bbl",
            "1e3-Sm3/Sm3",
            "1e3-Sm3/m3",
            "Mscf/STB",
            "Mscf/bbl",
        ]
        | None
    ) = Field(None, title="Gas Water Ratio Unit")
    id: int | None = Field(None, title="Id")
    ions: list[ExternalIonDataModel] | None = Field(None, title="Ions")
    location: Any = Field(None, title="Location")
    measured_depth: float | None = Field(None, title="Measured Depth")
    measured_depth_unit: Literal["m", "ft"] | None = Field(None, title="Measured Depth Unit")
    mud_base: Literal["Water", "Oil"] | None = Field(None, title="Mud Base")
    mud_sample_id: int | None = Field(None, title="Mud Sample Id")
    name: str | None = Field(None, title="Name")
    obm_composition: CompositionModel | None = Field(None, title="Obm Composition")
    obm_density: float | None = Field(None, title="Obm Density")
    obm_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Obm Density Unit"
    )
    obm_mw: float | None = Field(None, title="Obm Mw")
    pressure_at_lab: float | None = Field(None, title="Pressure At Lab")
    pressure_at_lab_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Pressure At Lab Unit")
    pressure_when_sampled: float | None = Field(None, title="Pressure When Sampled")
    pressure_when_sampled_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Pressure When Sampled Unit")
    recombined_fluid_composition: CompositionModel | None = Field(
        None, title="Recombined Fluid Composition"
    )
    recombined_fluid_contamination: float | None = Field(
        None, title="Recombined Fluid Contamination"
    )
    recombined_fluid_contamination_unit: Literal["mass%", "mole%"] | None = Field(
        None, title="Recombined Fluid Contamination Unit"
    )
    recombined_fluid_gor: float | None = Field(None, title="Recombined Fluid Gor")
    recombined_fluid_gor_unit: (
        Literal[
            "Sm3/Sm3",
            "Sm3/m3",
            "scf/STB",
            "scf/bbl",
            "1e6-Sm3/Sm3",
            "1e6-Sm3/m3",
            "MMscf/STB",
            "MMscf/bbl",
            "1e3-Sm3/Sm3",
            "1e3-Sm3/m3",
            "Mscf/STB",
            "Mscf/bbl",
        ]
        | None
    ) = Field(None, title="Recombined Fluid Gor Unit")
    recombined_fluid_mw: float | None = Field(None, title="Recombined Fluid Mw")
    reservoir_pressure: float | None = Field(None, title="Reservoir Pressure")
    reservoir_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Reservoir Pressure Unit")
    reservoir_temperature: float | None = Field(None, title="Reservoir Temperature")
    reservoir_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Reservoir Temperature Unit"
    )
    sampling_date: date | None = Field(None, title="Sampling Date")
    sep_gas_composition: CompositionModel | None = Field(None, title="Sep Gas Composition")
    sep_gas_mw: float | None = Field(None, title="Sep Gas Mw")
    sep_gor: float | None = Field(None, title="Sep Gor")
    sep_gor_unit: (
        Literal[
            "Sm3/Sm3",
            "Sm3/m3",
            "scf/STB",
            "scf/bbl",
            "1e6-Sm3/Sm3",
            "1e6-Sm3/m3",
            "MMscf/STB",
            "MMscf/bbl",
            "1e3-Sm3/Sm3",
            "1e3-Sm3/m3",
            "Mscf/STB",
            "Mscf/bbl",
        ]
        | None
    ) = Field(None, title="Sep Gor Unit")
    sep_oil_composition: CompositionModel | None = Field(None, title="Sep Oil Composition")
    sep_oil_density: float | None = Field(None, title="Sep Oil Density")
    sep_oil_density_unit: Literal["g/cm3", "kg/m3", "lbm/bbl", "lbm/ft3"] | None = Field(
        None, title="Sep Oil Density Unit"
    )
    sep_oil_mw: float | None = Field(None, title="Sep Oil Mw")
    sep_pressure: float | None = Field(None, title="Sep Pressure")
    sep_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Sep Pressure Unit")
    sep_temperature: float | None = Field(None, title="Sep Temperature")
    sep_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Sep Temperature Unit"
    )
    temperature_at_lab: float | None = Field(None, title="Temperature At Lab")
    temperature_at_lab_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Temperature At Lab Unit"
    )
    temperature_when_sampled: float | None = Field(None, title="Temperature When Sampled")
    temperature_when_sampled_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Temperature When Sampled Unit"
    )
    top_perforation_depth: float | None = Field(None, title="Top Perforation Depth")
    top_perforation_depth_unit: Literal["m", "ft"] | None = Field(
        None, title="Top Perforation Depth Unit"
    )
    transfer_pressure: float | None = Field(None, title="Transfer Pressure")
    transfer_pressure_unit: (
        Literal["bara", "barg", "psia", "psig", "kPaa", "kPag", "atm", "atmg"] | None
    ) = Field(None, title="Transfer Pressure Unit")
    transfer_temperature: float | None = Field(None, title="Transfer Temperature")
    transfer_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Transfer Temperature Unit"
    )
    true_vertical_depth: float | None = Field(None, title="True Vertical Depth")
    true_vertical_depth_unit: Literal["m", "ft"] | None = Field(
        None, title="True Vertical Depth Unit"
    )
    type: (
        Literal["REC", "SEP", "BHS", "OFT", "SEPO", "SEPG", "OBM", "GAS", "FLO", "WATER"] | None
    ) = Field(None, title="Type")
    water_conductivity: float | None = Field(None, title="Water Conductivity")
    water_conductivity_unit: Literal["micro-S/cm"] | None = Field(
        None, title="Water Conductivity Unit"
    )
    water_ph: float | None = Field(None, title="Water Ph")
    water_resistivity: float | None = Field(None, title="Water Resistivity")
    water_resistivity_unit: Literal["ohm-m"] | None = Field(None, title="Water Resistivity Unit")
    water_temperature: float | None = Field(None, title="Water Temperature")
    water_temperature_unit: Literal["C", "K", "F", "R"] | None = Field(
        None, title="Water Temperature Unit"
    )
    well_id: int | None = Field(None, title="Well Id")


class ExternalCreateSampleListModel(RootModel[list[ExternalCreateSampleModel]]):
    root: list[ExternalCreateSampleModel] = Field(..., title="CreateSampleListModel")


class ExternalCreateWellModel(BaseModel):
    basin_id: float | None = Field(None, title="Basin Id")
    field_id: float | None = Field(None, title="Field Id")
    field_segment_id: float | None = Field(None, title="Field Segment Id")
    formation_id: float | None = Field(None, title="Formation Id")
    formation_zone_id: float | None = Field(None, title="Formation Zone Id")
    id: int | None = Field(None, title="Id")
    location: Any = Field(None, title="Location")
    name: str = Field(..., title="Name")
    region_id: int = Field(..., title="Region Id")
    samples: list[ExternalCreateWellSampleModel] | None = Field(None, title="Samples")
    sub_basin_id: float | None = Field(None, title="Sub Basin Id")
    uwi: str | None = Field(None, title="Uwi")
